development:
  adapter: postgresql
  encoding: utf8
  database: useless-dev
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: useless-prod
  pool: 5
  username: 
  password: