development:
  adapter: postgresql
  encoding: utf8
  database: useless_dev
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: useless_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: useless_prod
  pool: 5
  username: 
  password: